import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';
import { glob } from 'glob';

async function generatePlaceholders() {
  console.log("Generating image placeholders...");
  
  const publicDir = path.join(process.cwd(), 'public');
  // Match standard image files in public directory (excluding SVG or ICO)
  const imageFiles = await glob('**/*.{png,jpg,jpeg,webp,avif}', { cwd: publicDir });

  const placeholders: Record<string, string> = {};

  for (const file of imageFiles) {
    try {
      const fullPath = path.join(publicDir, file);
      // Create a 10px wide base64 blurDataUrl
      const buffer = await sharp(fullPath)
        .resize(10, null, { fit: 'inside' })
        .toBuffer();
      
      const mimeType = `image/${path.extname(file).slice(1).replace('jpg', 'jpeg')}`;
      const base64 = `data:${mimeType};base64,${buffer.toString('base64')}`;
      
      // Store using the absolute public path (e.g., "/images/foo.jpg")
      placeholders[`/${file.replace(/\\/g, '/')}`] = base64;
    } catch (err) {
      console.error(`Failed to process ${file}:`, err);
    }
  }

  const outputPath = path.join(process.cwd(), 'src/lib/image-placeholders.ts');
  const fileContent = `// Auto-generated by scripts/generate-placeholders.ts\n\nexport const imagePlaceholders: Record<string, string> = ${JSON.stringify(placeholders, null, 2)};\n`;

  await fs.writeFile(outputPath, fileContent, 'utf-8');
  console.log(`Generated blurDataURLs for ${Object.keys(placeholders).length} images.`);
}

generatePlaceholders();
